repos:
  - repo: https://github.com/psf/black
    rev: 1b2427a2b785cc4aac97c19bb4b9a0de063f9547 # 24.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: cf1542cefa3e766670b2066dd75c4571d682a649 # 7.1.1
    hooks:
      - id: flake8
