repos:
  - repo: https://github.com/psf/black
    rev: 6fdf8a4af28071ed1d079c01122b34c5d587207a # 24.2.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 88a4f9b2f48fc44b025a48fa6a8ac7cc89ef70e0 # 7.0.0
    hooks:
      - id: flake8
